### ISSUE TITLE
add "+" icon does nothing

### ISSUE THREAD

**Issue by LindaLawton** [actions-on-google/smart-home-frontend#4]
The add button doesnt do anything it pops up a list of devices you can add but when i click on them nothing happens it just closes the window.

![image](https://user-images.githubusercontent.com/6592543/73266062-6fa34800-41d6-11ea-9d67-b59f3d4a0888.png)

# Update

I had to open up for the permissions on firebase.  

![image](https://user-images.githubusercontent.com/6592543/73267537-8ac38700-41d9-11ea-84c0-0f958cbf78f1.png)

This still doesnt register a device for a user but at least i can create them now.

**Comment by Fleker** [comment]
When you click on a device from the menu, it [makes an API call](https://github.com/actions-on-google/smart-home-frontend/blob/master/src/my-app.js#L402) to `${API_ENDPOINT}/smarthome/create`. Did you update the API endpoint value in [index.html](https://github.com/actions-on-google/smart-home-frontend/blob/master/index.html#L116)?

**Comment by LindaLawton** [comment]
yup the issue was that the firestore had false instead of true in the permissions.   should we have updated documentation to fix the permissions?   I dont know enough about cloud firestore to even know what thats doing.

**Comment by Fleker** [comment]
The documentation may need to be more clear about the permissions.

**Comment by tobi-coder** [comment]
I have the same problem. But even if I change the database permissions it doesn't work. Which seems to be obvious because I don't see a call to ${API_ENDPOINT}/smarthome/create. Any ideas where to search?

**Comment by proppy** [comment]
That looks like an (obsolete) issue with the Node.js backend, it shouldn't require extra permissions beyond what's documented at https://github.com/actions-on-google/smart-home-nodejs,
