### ISSUE TITLE
Is the service-worker's path correct?

### ISSUE THREAD

**Issue by seiga-k** [actions-on-google/smart-home-frontend#5]
https://github.com/actions-on-google/smart-home-frontend/blob/efc49ecb85517720569be069b3dac55dc4257d08/index.html#L95

This line said the ```service-worker.js``` is located under ```src```, but it seems now the file located on root directory.
Is it correct?

**Comment by Fleker** [comment]
Yeah that appears to be correct. As the service-worker just no-ops, it may have been missed in the refactor.

**Comment by proppy** [comment]
Obsolete.
