### ISSUE TITLE
Device is being created without field errorCode leading to fault in smart-home-java backend

### ISSUE THREAD

**Issue by murilobaliego** [actions-on-google/smart-home-frontend#6]
After creating Television device, an issue started happening on smart-home-java backend as the data model of television on Cloud Firestore was created without errorCode field.

After adding it manually in fire Cloud Firestore, the error was solved. Probably other devices will have the same issue.

**Comment by Fleker** [comment]
Does this only happen with TVs?

**Comment by murilobaliego** [comment]
No, I just created some other devices and it is happening with all of them, errorCode is not added in the data model.
